title = "abstract-booklet"
site_name = "abstract booklet"
site_url = "https://www.raynamharris.com/abstract-booklet"
github_repo = "https://github.com/raynamharris/abstract-booklet/"

add_pages = [ "index.md", "examples.md", "labels.md" ]

github_username = 'raynamharris'

issues_dump = 'abstract-booklet.dmp'

issue_title_prefix = 'Abstact: '
